### ISSUE TITLE
Update Python live task to 24a shipping feature

### ISSUE THREAD

**Issue by slevin48** [MathWorks-Teaching-Resources/Programming-A-Starter-Project-Using-MATLAB-and-Python#3]
With the Python live task now shipping in 24a, it might be good to remove the dependency to the GitHub repo implementing it, while leaving this option open for those who are still on an older release

**Comment by eszmw** [comment]
I thought I had, which is why there are two versions of most of the scripts. When you load the project, the proper instructions for the version of MATLAB that you are running should appear on your path and the others should be placed in Utilities/OldFiles. Can you tell me where you ran into the dependency?

**Comment by slevin48** [comment]
Hello Emma, my mistake, I was judging based on the screenshot of the live task on the README file

![](https://github.com/MathWorks-Teaching-Resources/Programming-A-Starter-Project-Using-MATLAB-and-Python/raw/release/Images/RunPythonLiveTask.png)

But I can see you have indeed upgraded the live script.

I had to search a little bit, but I found the version prior to 24a though: [https://www.mathworks.com/matlabcentral/fileexchange/116490-programming-a-starter-project-using-matlab-and-python](https://www.mathworks.com/matlabcentral/fileexchange/116490-programming-a-starter-project-using-matlab-and-python)
